In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.io import loadmat

In [2]:
data = pd.read_csv('input/auto-mpg[1].csv')
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [3]:
data.replace('?',np.nan, inplace= True)

In [4]:
# Check for missing values
data.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [5]:
## filling missing value with median
data['horsepower'] = pd.to_numeric(data['horsepower'], errors='coerce')

data['horsepower'].fillna(data['horsepower'].median(), inplace = True)

In [6]:
# Summary statistics
data.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.304020,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,38.222625,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,76.000000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,125.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000

In [7]:
data = data.drop(['car name'], axis=1)
target = data['mpg']
features = data.drop(['mpg'], axis=1) # axis=1 for columns

In [ ]:
# Selecting the features
from sklearn.feature_selection import SelectKBest, chi2, f_regression

select_k_best = SelectKBest(score_func=f_regression, k='all')
fit = select_k_best.fit_transform(features, target)

print("Selected features:", features.columns[select_k_best.get_support()])
print("Feature Scores:", select_k_best.scores_)

Selected features: Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model year', 'origin'],
      dtype='object')
Feature Scores: [597.07704785 724.99430337 589.63820515 888.85068265  84.95770025
 199.98200802 184.19963937]

### **Select K Best**

| Function/Class              | Task           | Works With                     | Best Use Case                                      |
|-----------------------------|---------------|--------------------------------|----------------------------------------------------|
| **f_classif**               | Classification | Continuous Features            | ANOVA F-value test for significance               |
| **mutual_info_classif**     | Classification | Any                            | Captures non-linear relationships                 |
| **chi2**                    | Classification | Non-negative categorical/count data | Feature selection based on chi-square test  |
| **f_regression**            | Regression     | Continuous Features            | ANOVA F-value test for regression                 |
| **mutual_info_regression**  | Regression     | Any                            | Captures non-linear relationships in regression   |
| **SelectPercentile**        | Any           | Any                            | Selects top X% of features                        |
| **SelectFpr**               | Any           | Any                            | Selects features based on a false positive rate  |
| **SelectFdr**               | Any           | Any                            | Controls false discovery rate                     |
| **SelectFwe**               | Any           | Any                            | Strict control of family-wise error rate         |
| **GenericUnivariateSelect** | Any           | Any                            | Customizable selection strategy                   |